name: Build

on: push

jobs:
  build:
    runs-on: linux
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - uses: android-actions/setup-android@v3
      - run: ./gradlew assembleRelease
      - id: apk
        run: echo "apkpath=$(find TeamCode/build/outputs/apk/release/*.apk)" >> $GITHUB_OUPUT
      - uses: actions/upload-artifact@v3
        with: 
          name: release-artifacts
          path: ${{ steps.apk.outputs.apkpath }}
