name: Test self-hosted runner


on: 
  push:

jobs:
  echo:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: echo
        run: which adb
      - name: connect
        run: adb connect 192.168.43.1
      - uses: actions/download-artifact@v3
        
